server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8085/
        predicates:
        - Path=/api/v1/**
      - uri: http://localhost:8084/
        predicates:
        - Path=/api/v2/**

